### ISSUE TITLE
[Feature]: Make a responsive navigation bar

### ISSUE THREAD

**Issue by AbhiPatel10** [AbhiPatel10/AISKCON-CONSTRUCTION#1]
Take a navbar design reference from this website.

https://www.panjetanibuildwell.com/

In Service Dropdown add below Types of Services

- Interior Designing
- Construction Management
- Seepage Analysis
- Consultancy Services
- Environmental Services
- Retrofication
- Destructive & NDT Testing

In Improvement and Repair Dropdown add below Types of Services

- Home repairs
- Kitchen repairs
- Bathroom repair
- Furniture repair
- Plumbing & pipes
- Appliance repairs

**Comment by techRajat** [comment]
Assign me this issue.

**Comment by pratyush6653** [comment]
> 

Assign me this issue

**Comment by AbhiPatel10** [comment]
@techRajat  Go ahead 👍

**Comment by techRajat** [comment]
@AbhiPatel10 ok bhaiya

**Comment by AbhiPatel10** [comment]
@pratyush6653  I will make issues soon, if you have any idea and you want to work on it so you can create an issue and start working on it
