### ISSUE TITLE
Improving after -hover effects

### ISSUE THREAD

**Issue by Tusharjoshi1703** [AbhiPatel10/AISKCON-CONSTRUCTION#103]
Please assign it to me .As the hover effects are not properly visible . I'll try to make it more visible and improve the UI.

**Comment by PayalPadmalyaPrusty** [comment]
@Tusharjoshi1703 I want to contribute.Please assign me

**Comment by PatilHarshh** [comment]
Hello ,
I'm harsh. I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away.

Skills
HTML5, CSS3, JS, Bootstrap | node js mongodb | Php, mysql | MERN | Responsive Design 

Can you please assign this issue to me. @AbhiPatel10
