### ISSUE TITLE
Favicon!

### ISSUE THREAD

**Issue by yashpreet2707** [AbhiPatel10/AISKCON-CONSTRUCTION#104]

**Comment by jainamthakkar** [comment]
if this issue is still open and no one is working on this than i wants to work on it

**Comment by yashpreet2707** [comment]
@jainamthakkar I've already made a PR btw.

**Comment by yashpreet2707** [comment]
hey maintainers, I'm really sorry for my mistake, out of curiosity I have made a PR without the issue being assigned to me. Now I know how this thing works.
So if possible can you please review this PR if you want to merge it please give the GSSoC'23 tag as well else wise you can close the PR. thanks for hearing me out :-)

**Comment by yashpreet2707** [comment]
@AbhiPatel10 Made the PR please review it. Thank you, have a good day ;-)

**Comment by Codemaster777** [comment]
Kindly assign this to me

**Comment by yashpreet2707** [comment]
@kartikayasija why didn't you merged it, can you please give suggestions if possible
