### ISSUE TITLE
Add smooth slide transition to all FAQs [GSSoc'23]

### ISSUE THREAD

**Issue by ChinatuL** [AbhiPatel10/AISKCON-CONSTRUCTION#107]
Hello. I noticed that when any question in the accordion in all the FAQs is clicked, the answer just pops up. I would like to improve this by adding a slide-down transition to the accordion. Kindly assign this issue to me as a Gssoc23 contributor.

![Screenshot (127)](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/97689140/88d38f75-c91d-4476-a9c7-289d823256e3)

**Comment by mudrikapandey** [comment]
Please assign this isssue to me under Gssoc'23.

**Comment by Apreksha** [comment]
Hello @AbhiPatel10. I'm a GSSoC'23 contributor. I can add transitions to the FAQs slides. Could you please assign me this task.

**Comment by deveshidwivedi** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project. Please assign it to me

**Comment by kartikayasija** [comment]
@ChinatuL Go ahead!

**Comment by ChinatuL** [comment]
@kartikayasija Thank you. Working on it immediately. Can you please add the Gssoc23 label? I am one of the contributors
