### ISSUE TITLE
Improve Fonts

### ISSUE THREAD

**Issue by shruti8302** [AbhiPatel10/AISKCON-CONSTRUCTION#109]
Hey @AbhiPatel10 
As a part of GSSOC'23,
I would like to change the font used in the website to create more impact on the user and I would also like to improve the footer section of the website. Kindly assign this issue to me.

**Comment by bleep123** [comment]
Hi,
I would like to work on this issue. Please assign it to me.

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by abcxyz31** [comment]
i can contribute to this pls assign me

**Comment by AbhiPatel10** [comment]
@shruti8302 Go Ahead, For this issue only work on Fonts and for footer make another issue

**Comment by shruti8302** [comment]
@AbhiPatel10 I have made a PR. Kindly look into it.

**Comment by Neha5679** [comment]
As a part of GSSOC'23,
I would like to improve the font, can you assign me.
