### ISSUE TITLE
Improving the readme file of this project 

### ISSUE THREAD

**Issue by harshsingh32** [AbhiPatel10/AISKCON-CONSTRUCTION#111]
I would like to work on improving the readme file of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by Anikinee** [comment]
I would like to work on this issue, please assign it to me under GSSoC'23.

**Comment by Apreksha** [comment]
Hello @AbhiPatel10. I'm a GSSoC'23 contributor. I want to improve readme file of this project. Could you please assign me this task.
