### ISSUE TITLE
Improving the aboutUs file 

### ISSUE THREAD

**Issue by harshsingh32** [AbhiPatel10/AISKCON-CONSTRUCTION#112]
I would like to improve the aboutUs file of this project making it engaging for the users. I would like to add some features and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by bleep123** [comment]
Hi,
I would like to work on this issue. Please assign it to me.

**Comment by PayalPadmalyaPrusty** [comment]
@harshsingh32 I want to contribute.Please assign me

**Comment by Apreksha** [comment]
Hello @AbhiPatel10. I'm a GSSoC'23 contributor. I want to improve about us page. Could you please assign me this task.

**Comment by kartikayasija** [comment]
@harshsingh32 Have you completed?

**Comment by AbhiPatel10** [comment]
@bleep123  You can work on this issue

**Comment by Monachaudhary** [comment]
I would like to work on it. I make sure you will love my work. Kindly assign this to me.
