### ISSUE TITLE
IMPROVEMENT in home page

### ISSUE THREAD

**Issue by Anikinee** [AbhiPatel10/AISKCON-CONSTRUCTION#114]
In the home page, the name of the Company i.e. "AISKCON-CONSTRUCTION" must be added in the beginning of the page also the footer must have a option to move to the front of the page. Also some changes related to CSS can be made on the hovering of images of "OUR SERVICES" part.

I would like to work on this issue, please assign it to me under GSSoC'23.

**Comment by shivam200446** [comment]
hey, I want to contribute to this issue, Please assign me this issue under GSSOC 23 .

**Comment by Apreksha** [comment]
Hello @AbhiPatel10. I'm a GSSoC'23 contributor. I want to improve Homepage. Could you please assign me this task.

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by Ashna56** [comment]
hey, this issue would be great for me as I am a beginner in open source. It will be great if you will assign this issue to me :)
