### ISSUE TITLE
Addition of Transition in Logo 

### ISSUE THREAD

**Issue by MohnishK7** [AbhiPatel10/AISKCON-CONSTRUCTION#118]
Can you please approve this issue and assign it to me under GSSOC'23?

add a transition button to the logo for navigation to the home screen

![add transition](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/90864490/d6b783b9-3b01-4a2f-b957-e60122f3c0e6)

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23
