### ISSUE TITLE
[Features] : Planning, construction and Rebuilding section

### ISSUE THREAD

**Issue by AbhiPatel10** [AbhiPatel10/AISKCON-CONSTRUCTION#12]
![image](https://user-images.githubusercontent.com/76242769/223939759-b3e1c7eb-1b30-4343-bf8f-40fadb199dea.png)

Take Inspiration from here :-  https://www.designesia.com/themes/buildpro/index.html

**Comment by rolikaagarwal** [comment]
Assign me this issue.
