### ISSUE TITLE
Footer section 

### ISSUE THREAD

**Issue by tanya2203** [AbhiPatel10/AISKCON-CONSTRUCTION#121]
containing additional information, links, and contact details to provide users with supplementary information and navigation options.

Within the footer, you may find various components, one of which is the "Contact Me" section. This section typically includes contact information such as an email address, phone number, or a contact form through which users can reach out to the website/app owner or administrator. 
Please assign me this issue .

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by PatilHarshh** [comment]
Hello ,
I'm harsh. I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away.

Skills
HTML5, CSS3, JS, Bootstrap | node JS, mongodb | Php, mysql | MERN | Responsive Design 

Can you please assign this issue to me. @AbhiPatel10

**Comment by itzanway** [comment]
please assign this task to me under GSSOC'23
