### ISSUE TITLE
Add link In navbar logo and make cursor pointer

### ISSUE THREAD

**Issue by jainamthakkar** [AbhiPatel10/AISKCON-CONSTRUCTION#122]
we should add home page link in navabar's logo and make the cursor to pointer on hover

i want to work on this issue !! please assign it to me

**Comment by AnmolChauhan123** [comment]
I also want to work on this issue...

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by Anjali07Patel** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by abcxyz31** [comment]
i want to contribute to this task
