### ISSUE TITLE
#Bug hovering on social links

### ISSUE THREAD

**Issue by jainamthakkar** [AbhiPatel10/AISKCON-CONSTRUCTION#123]
As you can see in this video when hovering on social links, `hr` is moving

https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/105544028/576cca84-682e-4640-ac00-5c4c603381ba

I want to work on this issue !!

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by AnmolChauhan123** [comment]
Assign this issue to me!!!!

**Comment by Ashna56** [comment]
Hey, I would like to work on this issue, this would be a great issue to solve for me as I am a beginner under GSSOC'23

**Comment by tarunprakashporam** [comment]
Hi there, I solved the bug and asked for pr #149

**Comment by jainamthakkar** [comment]
@AbhiPatel10 in this repo can i make pr without assignee or without raising an issue ??
