### ISSUE TITLE
Better background image for Services page

### ISSUE THREAD

**Issue by kanikakaur27** [AbhiPatel10/AISKCON-CONSTRUCTION#127]
@AbhiPatel10 The white font of the heading on the Services page is clashing with the background image. Allow me to improve the UI to make the heading stand out. Thanks!

![Screenshot 2023-05-20 at 11 13 24 PM](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/78797208/c1df5385-3063-4b1d-b68c-2fb61cce9050)

**Comment by Anjali07Patel** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.
