### ISSUE TITLE
Problem with repair dropdown menu

### ISSUE THREAD

**Issue by theDRB123** [AbhiPatel10/AISKCON-CONSTRUCTION#129]
Here i have observed that we dont require a repair dropdown menu in the navigation bar, instead we can keep all the repairs in a seperate repair section as the content for each of the repair option is very small and the dropdown bring unnecessary confusion.
allow me to fix this issue
Thanks .

**Comment by Anjali07Patel** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.
