### ISSUE TITLE
[Feature] : Why Choose us section 

### ISSUE THREAD

**Issue by AbhiPatel10** [AbhiPatel10/AISKCON-CONSTRUCTION#13]
![image](https://user-images.githubusercontent.com/76242769/223940006-a2bdc582-6d8d-4571-a289-1908825ae921.png)

Take inpiration from :- https://www.designesia.com/themes/buildpro/index.html

**Comment by kartikayasija** [comment]
@AbhiPatel10 Assign me this issue
