### ISSUE TITLE
Font Styling Does not blend well

### ISSUE THREAD

**Issue by theDRB123** [AbhiPatel10/AISKCON-CONSTRUCTION#130]
Across the entire website , we may notice that the font styling is not conveying the aspects very properly , the current fonts are small and are not very pleasing to look at
please allow me to resolve this issue.
Thank You.

**Comment by Anjali07Patel** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by ShubhangiBatra** [comment]
Sir please assign this task to me under GSSOC'23
