### ISSUE TITLE
[GGSoC'23]Side navigation bar

### ISSUE THREAD

**Issue by VC6378** [AbhiPatel10/AISKCON-CONSTRUCTION#133]
Hey,
As I have good hold on CSS,HTML and JavaScript, I can add side navigation bar to the website that can make it easier for the use to navigate.

**Comment by mvpfrever** [comment]
i can create a side nave bar easily please assign this to me it will be my pleasure if i work on it

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me under GSSOC'23.

**Comment by AbhiPatel10** [comment]
We do not need of the side navbar
