### ISSUE TITLE
Improving the Home page UI

### ISSUE THREAD

**Issue by sanketsaurav2411** [AbhiPatel10/AISKCON-CONSTRUCTION#135]
Hi @AbhiPatel10,
There quite a few things to add and change in the website.

Like:
-Navigation bar needs Improvement.
-"Scroll-to-Top" button
-And a few more alignments and visual appearance.

This will make the website more appealing.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me under GSSOC'23.

**Comment by khushi767** [comment]
I would like to work on this issue.Please assign me this issue
