### ISSUE TITLE
[GSSoC'23] Update Readme File

### ISSUE THREAD

**Issue by saiful64** [AbhiPatel10/AISKCON-CONSTRUCTION#136]
instead of  
```shell
 git clone https://github.com/<YOUR_GITHUB_USER_NAME>/mern_youtube_clone.git.
``` 

this should be in the project initialization to clone on local system
```shell
git clone https://github.com/<YOUR_GITHUB_USER_NAME>/AISKCON-CONSTRUCTION.git.
```

**Comment by Rutujeet** [comment]
I kindly request your consideration in assigning Issue #136 under GSSOC'23 to me. I am eager to take on this task and contribute to the project's success.

**Comment by AbhiPatel10** [comment]
Go ahead @Rutujeet

**Comment by Rutujeet** [comment]
Done and made a PR 👍

**Comment by saiful64** [comment]
> @Rutujeet Go ahead

I created the issue, I also provided with solution, I made a PR 19 hr ago.
Someone came afterwards made a PR is it possible??
How you guys are assigning in GSSoC'23????

**Comment by kartikayasija** [comment]
> > @Rutujeet Go ahead
> 
> I created the issue, I also provided with solution, I made a PR 19 hr ago. Someone came afterwards made a PR is it possible?? How you guys are assigning in GSSoC'23????

Sorry for this confusion @saiful64 , But this issue was already created before. You can work on any other issue.

**Comment by saiful64** [comment]
the merged issue #166 was created 9 hrs ago and mine #136 is created 2 days ago am I late or am I missing something??
I also created a PR #142 which is way before #166. Also abhi patel assigned me 9hrs ago how someone else pr is beign merged i dont know???  
As per GSSoC the rules were
1. Create issue
2. After the issue is assigned we have to subbmit the PR 

how you guys are doing....

**Comment by kartikayasija** [comment]
@saiful64 First of all, "update Readme File" issue was already created way before you created this, there was no need to create an issue.
Secondly, you raised the PR before the issue was assigned to you, means you did not follow the guidelines.
Third, this issue was not assigned to you because you didn't follow the guidelines. It is not necessary that the issue is assigned to the person who created it.

There's no need to argue.

**Comment by kartikayasija** [comment]
Because he followed contribution guidelines and you didn't.
