### ISSUE TITLE
[GSSoC'23] Add a scroll to top button 

### ISSUE THREAD

**Issue by nishita2104** [AbhiPatel10/AISKCON-CONSTRUCTION#137]
A scroll to top floating button would make the site more professional and add a functionality. Please assign this issue to me under GSSoC'23.

**Comment by jasleen1316** [comment]
hello, i would love to work on this!

**Comment by nishita2104** [comment]
Hi @jasleen1316 I rasied that issue and plan on working on it too, so if you could please find another issue, thanks!

**Comment by purviporwal0** [comment]
Pls assign this to me

**Comment by abhi-mis** [comment]
Hey I would Like to Work On this issues and Can You Please assign me This Task.

**Comment by AbhiPatel10** [comment]
@nishita2104 Go ahead

**Comment by nishita2104** [comment]
Thank you for assigning it to me.
