### ISSUE TITLE
Add License to Repository

### ISSUE THREAD

**Issue by ImranNawar** [AbhiPatel10/AISKCON-CONSTRUCTION#138]
Hi There!
I would like to create an issue in this GitHub project repository to address the need for adding a **license** and assigning it to myself. This will enable me to work on ensuring the project has a proper licensing framework. I would appreciate it if you could kindly assign this issue to me as part of the **GSSoC'23** program.

**Comment by AbhiPatel10** [comment]
go ahead @ImranNawar
