### ISSUE TITLE
Social media links [GSSoC'23]

### ISSUE THREAD

**Issue by DrVickie8** [AbhiPatel10/AISKCON-CONSTRUCTION#148]
I want to create social media pages and add the links.

When I opened this issue, the social links are opening to the homepage.

Please assign me to this

**Comment by PrachiChauhan23** [comment]
I want to add social media links .please assign me this.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me under GSSOC'23.

**Comment by jyoti145** [comment]
I would like to work on this issue.Please assign me this issue

**Comment by khushi767** [comment]
I would like to work on this issue.Please assign me this issue for gssoc'23

**Comment by DrVickie8** [comment]
Hey guys, how it works here is you go through the project and look out for new features to implement or bugs to fix.
When you find this, you go through the **issues** tab to check if someone else has shown interest in working on it, if someone has, then you move on to another feature to work on, and you keep doing this until you see that no one has expressed interest.

After this, you open a **new issue** and ask to be assigned to it.
Please don't go around asking to be assigned to an issue someone else opened, that will be a waste of time, because, for GSSoC '23, it works on a first-come, first-serve basis.

The only way this pattern will work is if that **issue** was opened by the maintainers, then you could have a chance if you know how to work on it.

**Comment by kartikayasija** [comment]
@DrVickie8 This issue is not needed as far as I know.

**Comment by DrVickie8** [comment]
Sure, noted.
