### ISSUE TITLE
Create a Frontend Folder [Gssoc'23]

### ISSUE THREAD

**Issue by ChinatuL** [AbhiPatel10/AISKCON-CONSTRUCTION#151]
Currently, there is a folder for the backend but none for the frontend. 

![Screenshot (131)](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/97689140/97b55296-1979-4c23-b05c-87a767e63145)

I would like to add all related folders into one frontend folder to tidy up the codebase. Kindly assign this issue to me as a Gssoc'23 contributor.

**Comment by AbhiPatel10** [comment]
For Now it's not needed it will create more issue in ongoing event
