### ISSUE TITLE
[GSSOC'23] adding hover to the Book us button 

### ISSUE THREAD

**Issue by purviporwal0** [AbhiPatel10/AISKCON-CONSTRUCTION#162]
adding hover to the Book us button and other similar buttons 
it will create an eye catching effect 
the hover effect will make the button expand a little bit

**Comment by airfusion64** [comment]
Hey @AbhiPatel10 , I can add a good hover button for the book us button. Can you please assign this task to me??

**Comment by chiki012** [comment]
hello, I'm good in the front-end part and able to add better design to this project. please assign me this issue.
