### ISSUE TITLE
[GSSOC'23]adding underline hover effect on the navbar options

### ISSUE THREAD

**Issue by purviporwal0** [AbhiPatel10/AISKCON-CONSTRUCTION#163]
I want to add underline effect upon hovering on the navbar icons
![Screenshot (6)](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/116807722/e39f7ab4-39a8-4d0a-ac13-904528b28b02)

**Comment by Vaani-pathariya** [comment]
Hello , I am a gssoc contributor , willing to work on this issue , please assign it to me !!

**Comment by khushi767** [comment]
Could you please assign me this as a GSSOC Contributor.
