### ISSUE TITLE
making the website available in all the languages worldwide.

### ISSUE THREAD

**Issue by Nishka30** [AbhiPatel10/AISKCON-CONSTRUCTION#167]
can you assign me this task @AbhiPatel10 ?

**Comment by Nishka30** [comment]
Actually sir the feature will make the website available in all the
languages making the user experience more comfortable.As not everyone
around the globe are familiar with English  .

**Comment by kartikayasija** [comment]
@Nishka30 This is not needed AFAIK, you can work on any other issue.
