### ISSUE TITLE
adding dark mode through a button in this website

### ISSUE THREAD

**Issue by Nishka30** [AbhiPatel10/AISKCON-CONSTRUCTION#168]
can you assign me this task? @AbhiPatel10

**Comment by nayan911** [comment]
hey can you assign this issue to me under GSSOC, everytime the user clicks on the button it will create a dark theme and if clicks again it will revert back to light theme.
Also i have worked on similar projects previously.
please assign this to me.

**Comment by kartikayasija** [comment]
@Nishka30 This issue is already assigned to someone.
