### ISSUE TITLE
improving contact section

### ISSUE THREAD

**Issue by lakshmiprasannakusumanchi** [AbhiPatel10/AISKCON-CONSTRUCTION#176]
I would like to improve the contact section please assign this to me under gssoc'23.

**Comment by AbhiPatel10** [comment]
@lakshmiprasannakusumanchi Are you wprking on this task ?

**Comment by Monachaudhary** [comment]
kindly assign this issue to me. I possess all the abilities this bug needs. I participate in GSSoC 2023. Kindly put this in GSSoC 2023.

**Comment by lakshmiprasannakusumanchi** [comment]
@AbhiPatel10 Yeah sorry for the late I will submit it by today.
