### ISSUE TITLE
Adding a scroll-to-top button [GSSOC'23]

### ISSUE THREAD

**Issue by deepeshgupta3257** [AbhiPatel10/AISKCON-CONSTRUCTION#178]
As your web page appear to be big you should add a scroll up arrow on your website for better experience.

Please assign this task to me I can work on this issue and fix is and also I'm a contributor for GSSoC '23.

**Comment by Sandeep0306** [comment]
HIi, I want to add scroll to top Button which will become easy for user to navigate to top of the page . Please assign me this issue under GSSOC'23.

**Comment by splusb** [comment]
I would like to work on this project under GSSOC'23. I am very much interested in this issue to add this scroll to top button which will improve the functionality of the webpage. So please assign me this issue.

**Comment by DhairyaMajmudar** [comment]
I would love to solve this issue under GSSoC'23. I can make a mind-blowing scroll-to-top button using HTML, and CSS

**Comment by kartikayasija** [comment]
This issue is already assigned to someone else.
