### ISSUE TITLE
Add a fav icon

### ISSUE THREAD

**Issue by deepeshgupta3257** [AbhiPatel10/AISKCON-CONSTRUCTION#179]
Adding a icon on web page helps the user to recognize the web page or the details of the web page of what it is about 
I can add a fav icon on your. 
So, Please assign this task to me I can work on this issue and fix is and also I'm a contributor for GSSoC '23.

**Comment by itzanway** [comment]
please assign this task to me under GSSOC'23

**Comment by DhairyaMajmudar** [comment]
I would love to solve this issue under GSSoC'23. I can add the favicon as mentioned
