### ISSUE TITLE
Hyperlinking the Environmental Services in the footer to its Heading

### ISSUE THREAD

**Issue by Vaani-pathariya** [AbhiPatel10/AISKCON-CONSTRUCTION#181]
I would like to hyperlink the environmental Services in the footer to its heading , and thus would want to be assigned this issue under Gssoc'23 tag

**Comment by AbhiPatel10** [comment]
@Vaani-pathariya are you working on this issue or we assign to someone else ?

**Comment by Vaani-pathariya** [comment]
I am working on the issue , I'll create a pull request very soon
