### ISSUE TITLE
Hire Us: redirect to Home 

### ISSUE THREAD

**Issue by dikshapadi** [AbhiPatel10/AISKCON-CONSTRUCTION#194]
Currently the hire Us button on click leads to the same Book appointment page, i would like to make a slight modification of redirecting to Home page after the filling up of the form.
Could @AbhiPatel10 you please assign me this task under GSSOC'23 ?

**Comment by kartikayasija** [comment]
@dikshapadi This issue is already assigned to someone, you can work on any other issue.

**Comment by dikshapadi** [comment]
@kartikayasija Sir, but i still dont see this change being reflected in the project, its been 2 days now
