### ISSUE TITLE
[GSSOC'23] - Clickable Website Logo Redirecting to home page to improve User Experience

### ISSUE THREAD

**Issue by VyjayantiN** [AbhiPatel10/AISKCON-CONSTRUCTION#199]
I am a GSSOC'23 contributor.

I suggest an effective improvement for the navbar. It would be beneficial to make the AISKCON logo on all pages clickable, directing users back to the home page when clicked. This  change would make navigation easier and provide a convenient way for users to return to the main page and enhance UX.

Please look into this issue and assign this to me under GSSOC'23.

**Comment by Aditya-Aware** [comment]
I have previously worked on this problem I wants to make my contribution under GSSOC's 23 program as Contributor.

**Comment by jainriya9** [comment]
Greetings!
I am a GSSOC'23 Contributor.

I would like to contribute for making the AISKCON logo clickable, which will redirect the users back to the homepage on clicking. In this way, it will be convenient for the users to get redirected to the main page quickly, enhancing the usability of the website. 

Kindly look into this issue and assign me under GSSOC'23. Looking forward to contribute. 

Thankyou so much!

**Comment by GeethaKoritala** [comment]
Just a few words of code. Could you assign me under GSSOC'23?

**Comment by Khushi-code031** [comment]
Hi @AbhiPatel10, Hope you're doing good!. To enhance and upgrade the user experience, I would like to contribute to the problem, as a part of the GSSOC'23. Please assign me this issue. 

Thank you!

**Comment by Hritik1503** [comment]
I am interested to work on this issue under GSSoC 2023 contributor so please assign me this task to me

**Comment by VyjayantiN** [comment]
Please assign me this issue under GSSOC'23.
