### ISSUE TITLE
[Feature]: Make Hire us section

### ISSUE THREAD

**Issue by AbhiPatel10** [AbhiPatel10/AISKCON-CONSTRUCTION#23]
![Screenshot from 2023-04-03 16-45-01](https://user-images.githubusercontent.com/76242769/229494047-55107bdc-9cd4-4c35-8805-76a992a7bf6f.png)

Take inspiration from https://goldengatecapital.netlify.app/

**Comment by kartikayasija** [comment]
@AbhiPatel10 Assign me this issue.

**Comment by AbhiPatel10** [comment]
Go ahead @kartikayasija 

Before you start building first check the place of this section ( https://goldengatecapital.netlify.app/ )
