### ISSUE TITLE
💡 [IMPROVE] - PAGE PERFORMANCE BY OPTIMIZING IMAGE ASSETS 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [AbhiPatel10/AISKCON-CONSTRUCTION#241]
| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    | The site uses `jpg` types of images, but the `jpg` images are always tend to be more larger in size so that the page takes more bandwith to load it |
| **Solution Proposed**      | My plan is to convert all those `jpg` images to `webp` to minimize the page load time and bandwith|
| **Additional Context**     | Unoptimized images severly affects page load time, because it may uncomfortable for the people who having a moderate internet connection|

### Checklists

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.
- [x] I am from `GSSoC'23`.
- [x] I would like to be assigned this task under `GSSoC'23`

**Comment by Neilblaze** [comment]
@0xabdulkhalid Sounds good. Go for it!

**Comment by 0xabdulkhalid** [comment]
> @0xabdulkhalid Sounds good. Go for it!

I need to assigned to go for it, so kindly assign me to this issue
