### ISSUE TITLE
Creating a better and more user friendly readme.md [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [AbhiPatel10/AISKCON-CONSTRUCTION#264]
The Readme file of this projects can be improved a lot. I has very less content and It can be made more systematic and some errors can be removed : 
![readmeissue](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/116020663/f404402d-43b7-45dd-9a6a-6b5ffb6c4343)

Please assign me this issue under GSSoC'23.

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23.

**Comment by Lavesh12** [comment]
please assign me this issue
