### ISSUE TITLE
BUG: Customer support image not showing [GSSOC'23]

### ISSUE THREAD

**Issue by ChinatuL** [AbhiPatel10/AISKCON-CONSTRUCTION#278]
I noticed that the image in the Contact With Our Experts section is not showing up.

![Screenshot (138)](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/97689140/6c8f1584-9691-44fb-9d64-9bf85182f5bc)

This is a result of a wrong src value in the image element. I would like to fix this. Kindly assign this issue to me as a Gssoc'23 contributor.

**Comment by kartikayasija** [comment]
Don't forget to sync your fork as contact section is updated.
