### ISSUE TITLE
Fix the text of "Book appointment" buttons

### ISSUE THREAD

**Issue by PoulavBhowmick03** [AbhiPatel10/AISKCON-CONSTRUCTION#291]
The alignment of "Book appointment" buttons in the repair and services pages look like this
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/133862694/69e6c572-ebe6-41b7-acb6-9604de47bfd0)

I want to fix this

**Comment by kartikayasija** [comment]
Also fix this, reduce the width.
<img width="854" alt="image" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/115306535/0cdf5ba4-3189-4298-9928-a3ed00b665c5">

**Comment by PoulavBhowmick03** [comment]
Okay!

**Comment by piyushlakheda** [comment]
Try to align all buttons, not at the center! Either Left-right or Right- left
and make sure all buttons looks similar like this one of Home repair
![Screenshot (127)](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/75446437/8865a711-6290-484c-a3f4-3f94ea91ca7d)

**Comment by PoulavBhowmick03** [comment]
Okay

**Comment by PoulavBhowmick03** [comment]
![image](https://github.com@piyushlakheda hiPatel10/AISKCON-CONSTRUCTION/assets/133862694/56ce80a2-1914-453b-8e75-5ccc781c91a4)

@piyushlakheda  is this ok? should I commit it?

**Comment by PoulavBhowmick03** [comment]
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/133862694/0896728d-bb9c-48f6-aae9-ec3190138469)

is this ok? should I commit it?

**Comment by PoulavBhowmick03** [comment]
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/133862694/bdd5ba4b-14ae-4964-95f0-b1d195ffa71c)

@piyushlakheda is this ok? should I commit it?
