### ISSUE TITLE
Make Contact Button Working...

### ISSUE THREAD

**Issue by rahulrana701** [AbhiPatel10/AISKCON-CONSTRUCTION#296]
right now this contact button on the home page is not working it should redirect to the contact section in the website.
<img width="954" alt="Screenshot 2023-06-03 151238" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/123585591/51c4718a-2f94-4d86-8a39-445c1cbb80fb">

**Comment by rahulrana701** [comment]
hi @AbhiPatel10 I would like to work on this issue could you please assign it to me.....

**Comment by kartikayasija** [comment]
Its Working @rahulrana701
