### ISSUE TITLE
Make a home page for the website

### ISSUE THREAD

**Issue by nishkarsh800** [AbhiPatel10/AISKCON-CONSTRUCTION#3]
- Make a detailed homepage for the website as per the design shared on slack.

**Comment by pratyush6653** [comment]
assign me this issue

**Comment by AbhiPatel10** [comment]
@pratyush6653 go ahead

**Comment by rolikaagarwal** [comment]
@AbhiPatel10  Assign me this issue.

**Comment by AmanMittal-3305** [comment]
Hii,
Please assign me this issue

**Comment by PayalPadmalyaPrusty** [comment]
@AbhiPatel10 assign me this issue

**Comment by Saloni581** [comment]
Kindly assign this issue to me under GSSoC'23.
