### ISSUE TITLE
[Feature] : Build with quality materials

### ISSUE THREAD

**Issue by AbhiPatel10** [AbhiPatel10/AISKCON-CONSTRUCTION#30]
![image](https://user-images.githubusercontent.com/76242769/229740639-5520231d-bdfe-4481-a7a5-2618a591e8cd.png)

Find Similar Image and use it.

**Comment by AbhiPatel10** [comment]
![image](https://user-images.githubusercontent.com/76242769/229742698-5c0536af-cd20-4628-b75c-cfdbf1ff1110.png)

**Comment by rolikaagarwal** [comment]
Assign me this issue.
