### ISSUE TITLE
Footer Design

### ISSUE THREAD

**Issue by ShreyaDhiman24** [AbhiPatel10/AISKCON-CONSTRUCTION#319]
Want to add black background to footer. (under GSSoC'23)

**Comment by Neilblaze** [comment]
I'd rather suggest dropping suggestions (such as low-level prototype designs) on how you're willing to bring changes to the current design. Once it gets approved, you'll be assigned & then can start working on it.

/cc: [#248](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/issues/248)  |  @pragati-3003

**Comment by ShreyaDhiman24** [comment]
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/98320971/78f90c4e-54e0-4a0b-91a6-2faf96937cdd)
Like this

**Comment by Neilblaze** [comment]
@ShreyaDhiman24 I feel that the current one looks *better*, minimalist & consistent with the theme (than the proposed one). I'm tagging this with `under review` and `help needed` labels for further consideration.

**Comment by ShreyaDhiman24** [comment]
hello! Is it not reviewed yet??

**Comment by Neilblaze** [comment]
Thanks for raising this PR, but unfortunately we've decided to not proceed with this design upgrade. Closing this.
