### ISSUE TITLE
[GSSOC'23] -Major issue - Missing image in the home screen

### ISSUE THREAD

**Issue by VyjayantiN** [AbhiPatel10/AISKCON-CONSTRUCTION#320]
The image in the container-expert section is missing and the alternate text is being displayed. Though, the picture is the img folder,it is not being displayed. 
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/106438430/b5bed6d9-14e8-49c6-8fa4-517bddbaaa7f)

I will remove this bug. Please assign me this issue under GSSOC'23

**Comment by VyjayantiN** [comment]
Please assign me this issue under GSSOC'23

**Comment by Nikhil743** [comment]
Please assign me this issue.

**Comment by Nikhil743** [comment]
Please assign me this issue.

**Comment by VyjayantiN** [comment]
@Neilblaze @AbhiPatel10 Please look into it.

**Comment by Neilblaze** [comment]
@VyjayantiN go ahead, raise the PR!
> P.S.: I'm currently away until June 12th, but I'll verify and confirm its validity once I'm back.

**Comment by VyjayantiN** [comment]
Thanks a lot @Neilblaze!!

**Comment by VyjayantiN** [comment]
@Neilblaze Please close this issue. Please check PR - #350

**Comment by Neilblaze** [comment]
⛔ Closing via #350 

P.S: @VyjayantiN, you have the authority to close the issue yourself once the connected PR is merged. There is no need to wait for mentor approval. This simplifies the process!
