### ISSUE TITLE
[GSSOC'23] - Missing heading in the hero section of about page

### ISSUE THREAD

**Issue by VyjayantiN** [AbhiPatel10/AISKCON-CONSTRUCTION#323]
The hero section of the about page is not displaying the heading on it due to which the user experience will get effected. All the other pages have this heading and due to this inconsistency is created among different pages of the same website. I would like to fix this issue. Look at the below about page. 
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/106438430/84cc427a-afed-4711-b452-65dbe885488d)
Look at the other pages : 
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/106438430/1dd4c40c-6f13-4b58-b17c-783dbb854a1b)
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/106438430/1fac2152-d7d5-4392-ab93-d03e5ba854e9)
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/106438430/9865906e-9494-4fa1-bfc9-155ae03ede7c)

**Comment by VyjayantiN** [comment]
Please assign me this issue under GSSOC'23.

**Comment by Neilblaze** [comment]
@VyjayantiN Go ahead and raise the PR!

**Comment by VyjayantiN** [comment]
@Neilblaze Please close this issue. check merged PR---  #346

**Comment by Neilblaze** [comment]
⛔ Closing via #346

> P.S: @VyjayantiN, you have the authority to close the issue yourself once the connected PR is merged. There is no need to wait for mentor approval. This simplifies the process!

**Comment by VyjayantiN** [comment]
Thanks for letting me know @Neilblaze!! I will do that from next time.
