### ISSUE TITLE
[GSSOC'23] - Missing formatting in the about us page

### ISSUE THREAD

**Issue by VyjayantiN** [AbhiPatel10/AISKCON-CONSTRUCTION#326]
The formatting of the about us page - our commitment section can be enhanced by increasing the readability. Bullets can be added before the words to make the words easy to read and enhance UX.
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/106438430/8487887f-3139-4e49-affa-f704d8e4c099)
Please assign me this issue.

**Comment by VyjayantiN** [comment]
Please assign me this issue under GSSOC'23.

**Comment by Nikhil743** [comment]
Please assign me this issue.
