### ISSUE TITLE
[GSSOC'23] -Adding a contributor.md file for improved collaboration and contribution guidelines.

### ISSUE THREAD

**Issue by VyjayantiN** [AbhiPatel10/AISKCON-CONSTRUCTION#341]
I propose adding a contributor.md file to the project's repository. This file will act as a comprehensive guide for potential contributors, providing clear instructions on the project's guidelines. Currently, new contributors often struggle to understand the project's contribution process, code conventions, and overall expectations.. The file would cover various aspects, such as an overview of the project's goals, setting up the development environment, contribution guidelines, code formatting, bug reporting, etc.

Proposed Solution:
To address the challenge of onboarding new contributors and improving collaboration, I suggest creating a contributor.md file in the project's repository. @Neilblaze @AbhiPatel10

**Comment by VyjayantiN** [comment]
Please assign me this issue under GSSOC'23.

**Comment by Neilblaze** [comment]
@VyjayantiN Go ahead!
