### ISSUE TITLE
Fix Grammar in Readme

### ISSUE THREAD

**Issue by Sriparno08** [AbhiPatel10/AISKCON-CONSTRUCTION#351]
There is a small typo in Readme.

![Screenshot 2023-06-10 184029](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/89148144/c4625389-54b4-4e12-a492-ef840b698a0c)

Fix:

helps -> help

I would like to work on this as part of GSSoC'23.

**Comment by harshitcompcode** [comment]
Assign me this issue

**Comment by rolikaagarwal** [comment]
@Sriparno08  Not needed as of now. Try to find a good issue.
