### ISSUE TITLE
[GSSOC'23] - Improper styling of the footer in About Page

### ISSUE THREAD

**Issue by VyjayantiN** [AbhiPatel10/AISKCON-CONSTRUCTION#354]
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/106438430/c34fc666-f4d8-44fc-a379-e4f235d21f98)
The elements are having two list styles. You assigned me this issue @kartikayasija. I will make the PR now. Please assign this to me under GSSOC'23.

**Comment by VyjayantiN** [comment]
Please assign me this issue under GSSOC'23.

**Comment by yash8917** [comment]
Assign me this issue under the GSSOC '2023

**Comment by VyjayantiN** [comment]
@Neilblaze @kartikayasija Please close this issue. It is already merged.
