### ISSUE TITLE
FAQ should not be in every page

### ISSUE THREAD

**Issue by sumitkr2000** [AbhiPatel10/AISKCON-CONSTRUCTION#356]
The faq section should not be on every page. It's not a good user experience.

**Comment by Diya28-mehra** [comment]
please assign me this issue.

**Comment by sumitkr2000** [comment]
@AbhiPatel10 Please assign me this issue so that I can start working on it.

**Comment by sumitkr2000** [comment]
@AbhiPatel10 Please assign me this issue so that I can start working on it.

**Comment by sumitkr2000** [comment]
@AbhiPatel10 Please assign me this issue so that I can start working on it.

**Comment by sumitkr2000** [comment]
@AbhiPatel10 Please assign me this issue so that I can start working on it.
