### ISSUE TITLE
Want to add color Themes in the website

### ISSUE THREAD

**Issue by lakhan06** [AbhiPatel10/AISKCON-CONSTRUCTION#362]
- I want that their should be a option so that user can select color theme of the website according to his/her choice and get a better user experience .
- I will add a themes option on the right side of each page and will change the color according to user choice by using JavaScript.
- I will uses root elements to change the color according to user choice.
- I will also stored the data of color theme in user local storage that user choose and when user again come on website then he will see the color theme according to his/her choice.

**Comment by TechTrendset** [comment]
Kindly consider assigning this project to me as I have already made significant contributions and invested time in understanding and implementing the required features. I am committed to delivering high-quality work and ensuring a positive impact. Thank you for your consideration.
