### ISSUE TITLE
Want to change the logo

### ISSUE THREAD

**Issue by tusharban42** [AbhiPatel10/AISKCON-CONSTRUCTION#367]

**Comment by silky-modi22** [comment]
I want to work on this issue under GSSOC 2023 please assign me 
![1](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/99467488/0dc4efd2-5818-4aac-a9ea-b48a4f1b746b)

**Comment by tusharban42** [comment]
@silky-modi22 I opened this issue so this should be assigned to me.

**Comment by tusharban42** [comment]
![Screenshot (71)](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/89680344/88362bfe-2855-4e68-a9ad-da1ddf180aca)

**Comment by kartikayasija** [comment]
Hello @tusharban42 @silky-modi22 Logo can not be changed, the company has already registered the logo.

**Comment by silky-modi22** [comment]
Ok, no problem.
