### ISSUE TITLE
[Feature] : Make same heading for all section

### ISSUE THREAD

**Issue by AbhiPatel10** [AbhiPatel10/AISKCON-CONSTRUCTION#37]
![image](https://user-images.githubusercontent.com/76242769/230292938-91819b85-1037-4dbc-9b1a-69f1781501d9.png)

Make the heading like this photo and remove arrow in mobile screen (responsive)

**Comment by AbhiPatel10** [comment]
First write code for one section only

**Comment by kartikayasija** [comment]
Assign me this issue

**Comment by AbhiPatel10** [comment]
Go ahead

**Comment by AbhiPatel10** [comment]
Leave this issue for someone 😅

@Akash-moon Will you take this issue ?

**Comment by Rutujeet** [comment]
@AbhiPatel10 Is the issue still open?
