### ISSUE TITLE
Change the background of Why choose us section

### ISSUE THREAD

**Issue by kartikayasija** [AbhiPatel10/AISKCON-CONSTRUCTION#370]
Share the background suggestions here.

**Comment by AnkitAnandMastery17** [comment]
Can you assign this to me?

**Comment by kartikayasija** [comment]
It is not matching with the theme, share some more.

**Comment by AnkitAnandMastery17** [comment]
ok.

**Comment by AnkitAnandMastery17** [comment]
<img width="869" alt="image" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/109721758/1993d2bd-ae24-41e9-8b4f-12914567165f">
<img width="882" alt="image" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/109721758/d11d7d95-c395-4273-9aac-f5044246ea63">

Is it alright?

**Comment by Malavi1** [comment]
Can I work on this parallel??

**Comment by Shiwani-Tehlan** [comment]
Hey, @kartikayasija ! 
Can you please assign me this issue?
I would like to work on this and  have some background suggestions to make. Attaching one below.
<img width="960" alt="AISKCON-Suggestion" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/109792126/770445f9-f293-490f-aa9f-971396f04566">

**Comment by dgarg6333** [comment]
#370  I want to work on this issue, kindly assign me this issue @kartikayasija 
#Change_the_background_of_Why_choose_us_section

**Comment by gkm0001** [comment]
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/121250607/76981b24-8ea4-442e-a5a8-6c9192ec4801)

Is this background image  matching with the theme ?

**Comment by dgarg6333** [comment]
<img width="946" alt="Screenshot 2023-06-24 122910" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/114967874/787c8ca2-a57e-4d2c-8a44-9cf180103c83">
<img width="948" alt="Screenshot 2023-06-24 122931" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/114967874/84e5cfbb-1b04-456a-8e2d-02d009849680">
<img width="953" alt="Screenshot 2023-06-24 122951" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/114967874/86e805e6-80f4-4f29-b789-baf5ed4cfa33">
above three background image matched with our website theme @kartikayasija please choose any one #370 kindly assign me this issue

**Comment by gkm0001** [comment]
![AISKCON-Construction](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/121250607/34f56f6e-fd50-49f0-ba6d-b51d116d2e43)


![AISKCON-Construction (1)](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/121250607/12242227-d69e-40a7-8d84-fa02ecaf2648)


![AISKCON-Construction (2)](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/121250607/9ef17d1a-65e9-40d9-a51f-a85ea66f257a)

I think these background images matched the theme of the website and give it very good look @kartikayasija  ,Kindly assign me  this issue.

**Comment by kartikayasija** [comment]
@gkm0001 Go for second one. Do add overlay

**Comment by gkm0001** [comment]
@kartikayasija Thank you for your guidance and support.
