### ISSUE TITLE
Addition of auto-comment.yml file

### ISSUE THREAD

**Issue by DivyanshiNarang** [AbhiPatel10/AISKCON-CONSTRUCTION#377]
We need to add an auto-comment.yml that will automatically welcome, greet and provide necessary information to the contributors when they create new issues, PR, and when these will get assigned or merged respectively. This will promote motivation and performance

@AbhiPatel10 *Please assign me this issue under gssoc'23*

**Comment by Nishitbaria** [comment]
hey @DivyanshiNarang  I have Already created this issue: https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/issues/282
please don't Make Duplicate issue

**Comment by DivyanshiNarang** [comment]
Hello @Nishitbaria, I didn't notice that. I will close my issue.

**Comment by Nishitbaria** [comment]
Thank you 👍🏻
