### ISSUE TITLE
Want to change the background image of Repairs section

### ISSUE THREAD

**Issue by silky-modi22** [AbhiPatel10/AISKCON-CONSTRUCTION#379]
The background image in Repairs section doesn't look good as much I want to change this image 
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/99467488/cf290541-b624-4727-a526-4a97536ea70e)
Please assign me this issue I want to work on this under GSSOC 2023

**Comment by dhananjayyedlabadkar** [comment]
I would like to work on this project . Please assign it to me.
