### ISSUE TITLE
[BUG] Favicon Icon is not showing on Index.html page and other pages.

### ISSUE THREAD

**Issue by gauravsingh1281** [AbhiPatel10/AISKCON-CONSTRUCTION#389]
<img width="959" alt="Screenshot 2023-06-18 132214" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/85905403/c925773a-fe85-4f87-b667-64f806abaa0b">
<img width="960" alt="Screenshot 2023-06-18 132529" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/85905403/f6a1b709-93fb-4c03-b067-5359eedf8704">

**Comment by gauravsingh1281** [comment]
@AbhiPatel10 Please assign this issue to me I want to work on it.

**Comment by kartikey129** [comment]
@AbhiPatel10 Please assign me this under gssoc'23 label.
Thank you

**Comment by gauravsingh1281** [comment]
@AbhiPatel10 Assign this issue to me because I have raised the issue first.

**Comment by chiragjaiswal20082002** [comment]
@AbhiPatel10 could you please grant me this opportunity to contribute on this issue and reflect changes with appropriate advice from you.
I would like to work on this project .Please assign it to me under GSSOC'23.
