### ISSUE TITLE
FAQ Section

### ISSUE THREAD

**Issue by kartikayasija** [AbhiPatel10/AISKCON-CONSTRUCTION#39]
@AbhiPatel10 Please tell which one will look good?

<img width="665" alt="image" src="https://user-images.githubusercontent.com/115306535/230326981-4860250c-ff70-4187-bd52-25add7d8cf82.png">
<img width="551" alt="image" src="https://user-images.githubusercontent.com/115306535/230327436-94e9eba7-219f-43f6-afa5-11d8295a0e2e.png">

**Comment by AbhiPatel10** [comment]
Can you please ask this in group so everyone can give their view
