### ISSUE TITLE
Add a Scroll Down Button

### ISSUE THREAD

**Issue by MahajanPreksha** [AbhiPatel10/AISKCON-CONSTRUCTION#392]
Hi, I'd like to add a Scroll Down button which leads to bottom of the page directly, just like Scroll Up Buttons directly helps the user reach the beginning of page. I want to add this feature. Please assign it to me under GSSoC'23.
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/121788863/6696558f-8727-4da4-9482-61085379d1d4)

**Comment by Neilblaze** [comment]
@MahajanPreksha may I know why as a user someone would require a _**scroll-to-bottom**_ button?

**Comment by Neilblaze** [comment]
Closing this since no feedback was received from the author. Feel free to re-open if needed.
