### ISSUE TITLE
Make the Slot Booking Page for the website

### ISSUE THREAD

**Issue by nishkarsh800** [AbhiPatel10/AISKCON-CONSTRUCTION#4]

**Comment by techRajat** [comment]
Assign me this issue.

**Comment by AbhiPatel10** [comment]
@techRajat  I left some comments on your pr so Please make changes accordingly. and Navbar is a most important part of website because we will use in every pages, so try to make it best of possible. 

By the way good going 🚀

Good luck 👍

**Comment by techRajat** [comment]
@AbhiPatel10 Ok bhaiya

**Comment by techRajat** [comment]
@AbhiPatel10 Assign me this issue.

**Comment by AbhiPatel10** [comment]
@techRajat Go ahead
