### ISSUE TITLE
In Repair Page , enhance the heading with background image

### ISSUE THREAD

**Issue by dgarg6333** [AbhiPatel10/AISKCON-CONSTRUCTION#412]
<img width="937" alt="Screenshot 2023-06-23 080040" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/114967874/86ff599e-99c1-4e7e-ab66-f68c9277369d">
Enhance the heading improvement and repair with the background image and the colour code match the background image also.....please assign me this issue sir #412 @Neilblaze @kartikayasija

**Comment by dgarg6333** [comment]
<img width="937" alt="Screenshot 2023-06-23 080040" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/114967874/01de8d8b-94fa-4ec2-8c2f-2a1ade9c84a9">
enhance the heading improvement and repair with the background image

**Comment by dgarg6333** [comment]
@kartikayasija I have done my task, please merge this #427

**Comment by anshujichaudhari** [comment]
I would like to work on this project. Please assign it to me.

**Comment by anshujichaudhari** [comment]
I would like to work on this project. Please assign it to me.

**Comment by Neilblaze** [comment]
@anshujichaudhari The issue has been fixed via #427, feel free to grab any other open issue / create your own.
