### ISSUE TITLE
On clicking Logo it should direct to home page

### ISSUE THREAD

**Issue by I-shika** [AbhiPatel10/AISKCON-CONSTRUCTION#413]
I want to add a feature to redirect to homepage on clicking the logo of the website. As it is generally a basic and important feature of a website. 
![Screenshot (49)](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/100770197/40dc24b8-ba76-40cb-93f6-a21b7b7fe640)

Please assign this issue to me under GSSOC'23

**Comment by gkm0001** [comment]
I want to work on this issue ,please assign me.

**Comment by kartikayasija** [comment]
This issue is already open
