### ISSUE TITLE
Add AISKCON name beside the logo 

### ISSUE THREAD

**Issue by Monishkaa** [AbhiPatel10/AISKCON-CONSTRUCTION#415]
@kartikayasija I wanted to add the AISKCON name beside the logo on the main page. Please assign it to me under **GSSOC'23**

**Comment by kartikayasija** [comment]
Can you elaborate this issue?

**Comment by Monishkaa** [comment]
<img width="694" alt="image" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/100695118/a599de4b-f111-4cdf-af73-625a258d0823">
 In this picture there is a space beside the logo, I want to write AISKCON there so that it looks more engaging.

**Comment by kartikayasija** [comment]
We have tried that, it was not looking good. So we decided to drop that.
