### ISSUE TITLE
enhance the featured work 

### ISSUE THREAD

**Issue by dgarg6333** [AbhiPatel10/AISKCON-CONSTRUCTION#430]
<img width="960" alt="Screenshot 2023-06-25 100057" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/114967874/1c587a9d-edf0-405c-9bcc-2b5f0c38940a">

 in above image , in the featured work hotel construction and all paragraph mentioned below the image is not centralised and  the background is not look good 
i would like to improve this , kindly assign me @kartikayasija @AbhiPatel10 @Neilblaze #430

**Comment by dgarg6333** [comment]
new one @kartikayasija @Neilblaze @AbhiPatel10 #430

<img width="941" alt="Screenshot 2023-06-25 121331" src="https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/114967874/3ee5fd3f-ea1d-4df3-a8ec-8e312e315741">

**Comment by dgarg6333** [comment]
@kartikey129 may i work on this change #430

**Comment by Neilblaze** [comment]
Go ahead @dgarg6333

**Comment by dgarg6333** [comment]
I completed my task , kindly merge my pull request #435 
@Neilblaze @kartikayasija
