### ISSUE TITLE
redesign the interior-designing page [GSSOC'23]

### ISSUE THREAD

**Issue by shivaniyuvrajyadav** [AbhiPatel10/AISKCON-CONSTRUCTION#432]
images are not aligned properly on this page.
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/112896644/f2a0d454-af9b-4f27-a516-f2f67d6a7a97)

**Comment by kartikayasija** [comment]
Everything is working properly, check in github pages deployment
