### ISSUE TITLE
Favicon Missing on Secondary Pages.

### ISSUE THREAD

**Issue by Raunak-Srivastava** [AbhiPatel10/AISKCON-CONSTRUCTION#437]
Currently, the favicon is only displayed on the home page, but it is not visible on any of the secondary pages.
I would like to work on this issue and contribute the necessary changes to resolve the favicon inconsistency problem.

Kindly assign me this issue under GSSoC'23 @Neilblaze @kartikey129 @AbhiPatel10

**Comment by Neilblaze** [comment]
Good catch! Go ahead! @Raunak-Srivastava

**Comment by Raunak-Srivastava** [comment]
I have done all the necessary changes. Please merge my pull request #438 @Neilblaze
