### ISSUE TITLE
Some UI Enhancement in Home Page

### ISSUE THREAD

**Issue by soubhik-111** [AbhiPatel10/AISKCON-CONSTRUCTION#441]
I want to do some Enhancement in UI in Mobile

1. 
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/90599826/a7f69bfe-34c2-4842-ae96-2a655c878e2d)

2.
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/90599826/5ed23a28-dbe0-48ed-995e-d3df2854002e)

**Comment by soubhik-111** [comment]
There is one more 
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/90599826/f889e165-5138-42c5-8b69-e746c1129723)

Kindly assign me Under GSSOC'23

**Comment by Neilblaze** [comment]
@soubhik-111, could you please list down the modifications you suggest to incorporate as an improved update?

**Comment by soubhik-111** [comment]
Expected Changes are 
1. Icons to be aligned in the same line.
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/90599826/333e099d-df59-4383-ac31-91a3e423523d)

2. Chatbot and go to the top button align vertically, So overlapping of content decreases.
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/90599826/db81c4bc-b057-4f16-9b42-b58e7fd86501)

3. Make the two buttons in a line and make the center.
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/90599826/75dae1a5-cdb7-45c6-8de1-602d3ef004b6)

4. Make the card looks better by giving the appropriate space required 
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/90599826/5d6ed23d-c255-4ff8-b18d-eea88780ce22)

@Neilblaze If you have any feedback on these changes or you have some better ideas do share them with me I will look into that.

**Comment by Neilblaze** [comment]
Looks good, go ahead! @soubhik-111
