### ISSUE TITLE
Adding a github icon in Footer

### ISSUE THREAD

**Issue by marshadkhn** [AbhiPatel10/AISKCON-CONSTRUCTION#447]
Hey @Neilblaze , @AbhiPatel10 and @kartikayasija
I gone through all the assigned and unassigned issue in AISKCON-CONSTRUCTION and checked the whole website
While testing the website I found a basic add on in the footer section
Footer contain the social media links, that one link is missing of **GITHUB**

### Footer now
![Screenshot 2023-06-29 231825](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/80325579/fec767af-7478-4123-9c6b-7afc4d1f3fcf)

### Footer should be
![Screenshot 2023-06-29 232959](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/80325579/b43e4bea-d5d5-4def-b4f2-e1bf5a59ee85)

### _Assign me this basic add-on

**Comment by Raunak-Srivastava** [comment]
I would like to work on it. I will also link to their respective links if you will provide me the social media handles.
Please assign me this under GSSoC'23. @Neilblaze @AbhiPatel10 @kartikey129

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it

**Comment by marshadkhn** [comment]
Guys open your own issues

**Comment by Vaishwanavi** [comment]
please assign me this issues under GSSOC'23.I would like to work on it.
