### ISSUE TITLE
Our Projects section

### ISSUE THREAD

**Issue by techrajat** [AbhiPatel10/AISKCON-CONSTRUCTION#45]
![Screenshot (159)](https://user-images.githubusercontent.com/118634923/230467066-050670c2-856e-4dd2-9527-4ee6afc1dc78.png)

**Comment by Nishannaik** [comment]
Can I work on this issue @techrajat

**Comment by Nishannaik** [comment]
please assign me under gsoc 23

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me under GSSOC'23.
