### ISSUE TITLE
[Docs] Fixing heading and typo Issues in `README.md`

### ISSUE THREAD

**Issue by jfmartinz** [AbhiPatel10/AISKCON-CONSTRUCTION#465]
I would like to address two issues in the README file. Firstly, the heading is not displaying correctly or behaving as intended, and I would like to fix that. Secondly, there is a typo in the README file that needs to be corrected. It should be `dependency` or `dependencies` . I want to bring these issues to your attention so that they can be resolved. Thank you.

assign this to me under gssoc23

first issue: 
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/129386460/9cbbd1ac-79d6-456a-bfa7-35f9345f2468)
second issue:
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/129386460/c89c6ace-67c6-436a-a3ff-39292148eb93)

**Comment by jfmartinz** [comment]
can you check @AbhiPatel10

**Comment by Neilblaze** [comment]
@jfmartinz Go ahead!
