### ISSUE TITLE
About us Page

### ISSUE THREAD

**Issue by kartikayasija** [AbhiPatel10/AISKCON-CONSTRUCTION#47]

**Comment by pratyush6653** [comment]
assign me this issue

**Comment by kartikayasija** [comment]
@pratyush6653 I have completed it👍

**Comment by AbhiPatel10** [comment]
@kartikayasija That's wrong, don't do like this if you are working on it then get assign that issue first.

@pratyush6653 Find another issue and work on it

**Comment by kartikayasija** [comment]
@AbhiPatel10 Sorry for this.
