### ISSUE TITLE
[bug]: fix hover animation delay

### ISSUE THREAD

**Issue by Neilblaze** [AbhiPatel10/AISKCON-CONSTRUCTION#474]
Follow the gif 👇🏼 

![screx](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/48355572/09e2aa92-158f-4290-98ee-2109f12f6f12)

**Solution:** The *delay* of animation should be uniform for each card. The bug can be explored [here](https://abhipatel10.github.io/AISKCON-CONSTRUCTION/).

/cc: @kartikayasija, @AbhiPatel10

**Comment by UdhbhavSinghRana** [comment]
Can you tell me which animation timing do you want all of them to have ?

**Comment by Neilblaze** [comment]
@UdhbhavSinghRana First one from left.

**Comment by UdhbhavSinghRana** [comment]
@Neilblaze can you please see my pr?
