### ISSUE TITLE
Bug in Footer

### ISSUE THREAD

**Issue by marshadkhn** [AbhiPatel10/AISKCON-CONSTRUCTION#480]
Hey @AbhiPatel10 and @Neilblaze 
While checking the project project I found a bug in footer section that is `github` button is link less
As we have repo so we can put github link to project too
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/80325579/f521cb36-d2a0-4940-a4d9-27bb40ad00b0)

**Comment by Neilblaze** [comment]
I'm afraid that we're lacking social links atm. Meanwhile, feel free to raise a PR to link the GitHub repo with the site.

**Comment by marshadkhn** [comment]
Sure

**Comment by Shanukumar2929** [comment]
Can you please assign me this issue under gssoc'23??

**Comment by marshadkhn** [comment]
please read the whole conversation carefully!

**Comment by Sannitya-13** [comment]
Please issue it to me..
I will solve it...and give me some more too

**Comment by MohanaSrinivas** [comment]
i would like to work on this project please assign to me.

**Comment by Rajeevjewar** [comment]
Hello @marshadkhn,
I am interested in contributing to this project and I would like to request permission to work on the (Bug in Footer #480) issue. If possible, could you please assign this issue to me?
