### ISSUE TITLE
Enabling lazy loading

### ISSUE THREAD

**Issue by marshadkhn** [AbhiPatel10/AISKCON-CONSTRUCTION#481]
Hey @Neilblaze and @AbhiPatel10 
I want to put a new feature to website that is enabling lazy loading to website
**Lazy loading is the practice of delaying load or initialization of resources or objects until they're actually needed to improve performance and save system resources.** 

### Advantage of lazy loading
- Better data fetching
- Better user experience
**and many more**

**Example**
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/80325579/1631510f-8d4d-468f-8b34-917a34f3b2b5)

Showing a structure while the data is loading!
**_Assign me this issue under GSSOC'23_**

**Comment by Neilblaze** [comment]
This is being tackled in #451

**Comment by marshadkhn** [comment]
OK Sorry I didn't see
