### ISSUE TITLE
Put the Contributing guidelines in the separate folder 

### ISSUE THREAD

**Issue by nishkarsh800** [AbhiPatel10/AISKCON-CONSTRUCTION#5]
- In that folder add the contributing guidelines in brief.

**Comment by shraddha761** [comment]
Hye
please assign me this issue

**Comment by krittika2004** [comment]
Please assign this issue to me @nishkarsh800

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by Yogesh-7523** [comment]
sir can you assign this to me?
