### ISSUE TITLE
adding hovering in the faq section

### ISSUE THREAD

**Issue by harshita-2003** [AbhiPatel10/AISKCON-CONSTRUCTION#501]
At moment FAQ section of the site does not have any hovering effect to enhance the effect

**Comment by hansupadhyay007** [comment]
Hi @harshita-2003 
Can you please assign this task to me under gssoc 2023 label. I will complete it as soon as possible.

**Comment by Yukti-Mehta** [comment]
Can you please assign this task. I will complete it as soon as possible.

**Comment by kundan766** [comment]
Hey,@harshita-2003
I have solved the issue in my local repo. can you please assign me the issue so that i can able to make pull request  as soon as possible.

**Comment by Salonijain2210** [comment]
please allow me the opportunity to resolve this issue .

**Comment by sonalisdas** [comment]
Hello, I'm a GSSoC'24 contributor and wish to work on this issue.

**Comment by harshita-2003** [comment]
@sonalisdas  try observing the site and find mistakes or changes in that , and open new issue that would be more preferrable by the maintainers.
