### ISSUE TITLE
[Feature Request] Adding a Contributors list to the website 

### ISSUE THREAD

**Issue by Sch476** [AbhiPatel10/AISKCON-CONSTRUCTION#503]
I would like to add a contributors list to the website. By adding it to the website, we can showcase the contributors who worked in this project.

**Comment by Sch476** [comment]
@Neilblaze  I wanted to work on this issue but you assigned someone else ??

**Comment by Neilblaze** [comment]
@Sch476 fyi @kartikayasija is also a mentor.

**Comment by Sch476** [comment]
Oh my bad sorry @Neilblaze 

But once you finish the confirmation can you assign it to me ?

**Comment by Sch476** [comment]
@Neilblaze Can I work on this issue now  ??

**Comment by Neilblaze** [comment]
@Sch476 I'm currently out due to some obligations, I'd recommend waiting for @kartikayasija's signal
