### ISSUE TITLE
Update the Readme

### ISSUE THREAD

**Issue by nishkarsh800** [AbhiPatel10/AISKCON-CONSTRUCTION#6]
- Update the readme so that it may be interactive with the users

**Comment by prernadabi23** [comment]
Hello @nishkarsh800 Can I take on this issue?

**Comment by krittika2004** [comment]
@nishkarsh800 Kindly assign this issue to me

**Comment by PriyankaTamhankar01** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23
