### ISSUE TITLE
General Consulting  Page

### ISSUE THREAD

**Issue by rolikaagarwal** [AbhiPatel10/AISKCON-CONSTRUCTION#61]
![image](https://user-images.githubusercontent.com/81984963/230751852-6d26f047-718f-43ea-8d72-360b3b6dcaa1.png)

**Comment by prernadabi23** [comment]
Hello @rolikaagarwal I would like to work on this issue.

**Comment by prernadabi23** [comment]
@rolikaagarwal Can you give me an instance of what needs to be done here? That would be very helpful.
