### ISSUE TITLE
[Feature] : Make testimonial Section

### ISSUE THREAD

**Issue by AbhiPatel10** [AbhiPatel10/AISKCON-CONSTRUCTION#7]

**Comment by kartikayasija** [comment]
assign me this issue

**Comment by AbhiPatel10** [comment]
![image](https://user-images.githubusercontent.com/76242769/229494530-36be83b3-73b2-4e7a-9dd6-9ef259cf3ba8.png)


You can take inspiration from https://goldengatecapital.netlify.app/
