### ISSUE TITLE
[Features] : Make contact with our expert page

### ISSUE THREAD

**Issue by AbhiPatel10** [AbhiPatel10/AISKCON-CONSTRUCTION#8]
It's should look like this but you can also make as per your creativity.

![image](https://user-images.githubusercontent.com/76242769/222974340-86f1e825-0ad9-4bf1-b43e-c932186e13aa.png)

**Comment by rolikaagarwal** [comment]
Assign me this issue

**Comment by AbhiPatel10** [comment]
@rolikaagarwal  Great, go ahead 👍

**Comment by rolikaagarwal** [comment]
Okay
